# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169On4TH2i7xxyYbXffeEeGX4LFQiypJ2
"""

import pandas as pd

# Direct URL to the HDX dataset found
url = "https://data.humdata.org/dataset/98dea0b7-3d7d-4ac1-90d6-8b1f19b9b757/resource/57cb3e00-30cf-4218-ad91-86ccdaa19c4e/download/energy-and-mining_ken.csv"

print("Connecting to HDX and downloading data... please wait a moment.")

# Load the data directly from the live web link
df = pd.read_csv(url)

print("Success! Dataset loaded completely.")
print("-" * 50)
print("Here are all the unique indicator names available in your file:")
print("-" * 50)

# Print all unique indicators so we see their exact spelling in this specific file
for indicator in df['Indicator Name'].unique():
    print(f"- {indicator}")

# 1. Defined the exact indicators we want based on the file's structure
my_baseline_indicators = [
    "Energy intensity level of primary energy (MJ/$2021 PPP GDP)",
    "Access to electricity (% of population)",
    "Combustible renewables and waste (% of total energy)"
]

# 2. Filtered the main dataset
filtered_baseline = df[df['Indicator Name'].isin(my_baseline_indicators)]

# 3. Sorted by Indicator Name and Year so it's beautifully organized
filtered_baseline = filtered_baseline.sort_values(by=['Indicator Name', 'Year'])

# 4. Saved this to a brand new CSV file in your Colab environment
filtered_baseline.to_csv("kenya_energy_baseline.csv", index=False)

print("Baseline dataset 'kenya_energy_baseline.csv' created successfully!")
print("-" * 50)
print("Quick preview of your filtered data:")
print(filtered_baseline.head(10))

from google.colab import files

# This will force Google Colab to push the file directly to your browser's download queue
files.download("kenya_energy_baseline.csv")

